module.exports = {
  res: require('b2b-response'),
  experts: require('b2b-managers'),
  repositories: require('./repositories'),
  dbRedis: require('./redis-repositories'),
  taxCalculator: require('./taxCalculator'),
  taxType: require('./taxType'),
  strategy: require('./order'),
  builder: require('./builder'),
  discountsHandler: require('b2b-discounts'),
  elasticSearchRepositories: require('b2b-aws-elasticsearch'),
  Query: require('./elasticPortfolioBuilder'),
  connection: require('./elasticRepositories'),
  elasticPortfolioPrice: require('./elasticPortfolioPriceData'),
  awsRepositories: require('./aws.repositories'),
  getTableNames: require('./aws.config'),
  accessControl: require('b2b-access-control'),
  Cognito: require('./cognito'),
  getSourceChannel: require('./getSourceChannel'),
  rounding: require('b2b-rounding'),
  taxesHandler: require('b2b-taxes'),
  groupBy: require('./lodash-impl'),
  elasticMapper: require('./elasticMapper'),
};
