const productsMocks = [
  {
    name: 'Coca Cola retornable 2.5l',
    productId: '001AR3043-CC-R-2.5-PET',
    cpgId: '001',
    countryId: 'AR',
    organizationId: '3043',
    productErpId: 'CC-R-2.5-PET',
    locked: false,
    availability: true,
    brand: 'Coca Cola',
    package: 'PET',
    returnability: true,
    image: null,
    deleted: false,
    createdBy: 'andres.reynoso',
    createdTime: '2020-11-04T18:27:57.000Z',
    updatedBy: null,
    updatedTime: null,
  },
  {
    name: 'Coca Cola retornable 2.5l',
    productId: '001AR3043-CC-R-2.5-PETS',
    cpgId: '001',
    countryId: 'AR',
    organizationId: '3043',
    productErpId: 'CC-R-2.5-PETS',
    locked: false,
    availability: true,
    brand: 'Coca Cola',
    package: 'PET',
    returnability: true,
    image: null,
    deleted: false,
    createdBy: 'andres.reynoso',
    createdTime: null,
    updatedBy: null,
    updatedTime: null,
  },
];

module.exports = { productsMocks };